apiVersion: v1

kind: Service

metadata:
  name: item-api-service
  labels:
    app: item-api

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: item-api
